version: "3.7"
services:

  cardano:
    build:
      context: ./images/cardano
    ports:
      #- "8080:8080"
      #- "8080:8080"
      #- "8080:8080"
      #- "8080:8080"
      #- "8080:8080"
      - "8090:8090"
      - "8091:8091"
      - "8190:8190"
    volumes:
      #- ./config/cardano/configuration.yaml:/ada/configuration.yaml:ro
      - cardano-data:/ada/data
    command:
      - "--address 0.0.0.0:3003"
      - "--listen  0.0.0.0:3003"
      - "--db-path /ada/data/db"
      - "--web"
      - "--web-port 8083"
      - "--wallet-address 0.0.0.0:8093"
      - "--wallet-db-path /ada/data/wallet-db"

  cardano-explorer:
    build:
      context: ./images/cardano
    ports:
      #- "8080:8080"
      #- "8080:8080"
      #- "8080:8080"
      #- "8080:8080"
      - "8080:8080"
      #- "8090:8090"
      #- "8190:8190"
    command:
      - /cardano-sl/test-explorer
    volumes:
      # - ./config/cardano/configuration.yaml:/cardano-sl/lib/configuration.yaml:ro
      - cardano-data:/ada

  dash:
    image: dashpay/dashd
    restart: always
    expose:
      - "9998"
      - "9999"
    ports:
      - "19998:19998"
      - "19999:19999"
    volumes:
      - ./config/dash.conf:/dash/.dashcore/dash.conf:ro
      - dash-data:/dash/.dashcore

volumes:
  cardano-data:
  dash-data:

